<?php

namespace Acme\Bundle\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvoicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoicesRepository extends EntityRepository
{

	//repository function to fetch data relative in invoice and invoicelineitems tables.  
	public function getAllInvoicesByClients($clientId){
		
		$sql = 'SELECT * FROM invoices 
				INNER JOIN invoicelineitems ON invoices.invoice_num = invoicelineitems.invoice_num 
				WHERE client_id LIKE :id';
		$params = array(
		'id' => '%'.$clientId.'%',
		);

	return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
	}
}
